In [59]:
# Title: CT03 - Unsharp Masking
import numpy as np
def round(avg):
    frac = avg - np.floor(avg)
    sign = np.sign(avg)
    if abs(frac) < 0.5:
        roundup = np.floor(abs(avg))
    else:
        roundup = np.ceil(abs(avg))
    return sign*roundup

image = np.array([[4,3,5],[3,6,2],[5,4,7]])
print("Original image:")
print(image)

print("\nKernel:")
kernel = np.array([[1,2,1],[2,4,2],[1,2,1]])
print(kernel,end="\n\n")


blurred = image.copy()
#pad the image with zeros
blurred = np.pad(blurred,1,mode='constant',constant_values=0)
for i in range(1,blurred.shape[0]-1):
    for j in range(1,blurred.shape[1]-1):
        temp = blurred[i-1:i+2,j-1:j+2]
        values = temp*kernel
        for e in range(values.shape[0]):
            for f in range(values.shape[1]):
                print(values[e,f],end=" ")
                if e == values.shape[0]-1 and f == values.shape[1]-1:
                    print("=",end=" ")
                else:
                    print("+",end=" ")
        sum = np.sum(values)
        print(sum,end=" ")
        sum = sum / 16
        print("=",sum,end=" ")
        rounded = round(sum)
        print("=",rounded,end="\n")
        blurred[i,j] = rounded
        
#remove the padding
blurred = blurred[1:-1,1:-1]
print("\nBlurred image:")
print(blurred)

#mask of image 
mask = image - blurred
print("\nMask:")
print(mask)

#output image with k=2.5
k = 2.5
output = np.zeros(image.shape)
for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        output[i,j] = round(image[i,j] + k*mask[i,j])

print("\nOutput image:")
print(output)

Original image:
[[4 3 5]
 [3 6 2]
 [5 4 7]]

Kernel:
[[1 2 1]
 [2 4 2]
 [1 2 1]]

0 + 0 + 0 + 0 + 16 + 6 + 0 + 6 + 6 = 34 = 2.125 = 2.0
0 + 0 + 0 + 4 + 12 + 10 + 3 + 12 + 2 = 43 = 2.6875 = 3.0
0 + 0 + 0 + 6 + 20 + 0 + 6 + 4 + 0 = 36 = 2.25 = 2.0
0 + 4 + 3 + 0 + 12 + 12 + 0 + 10 + 4 = 45 = 2.8125 = 3.0
2 + 6 + 2 + 6 + 24 + 4 + 5 + 8 + 7 = 64 = 4.0 = 4.0
3 + 4 + 0 + 8 + 8 + 0 + 4 + 14 + 0 = 41 = 2.5625 = 3.0
0 + 6 + 4 + 0 + 20 + 8 + 0 + 0 + 0 = 38 = 2.375 = 2.0
3 + 8 + 3 + 4 + 16 + 14 + 0 + 0 + 0 = 48 = 3.0 = 3.0
4 + 6 + 0 + 6 + 28 + 0 + 0 + 0 + 0 = 44 = 2.75 = 3.0

Blurred image:
[[2 3 2]
 [3 4 3]
 [2 3 3]]

Mask:
[[ 2  0  3]
 [ 0  2 -1]
 [ 3  1  4]]

Output image:
[[ 9.  3. 13.]
 [ 3. 11. -1.]
 [13.  7. 17.]]
