In [36]:
# Mean filter(Linear)
import numpy as np

# input 2D array
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
image = np.array(entries).reshape(row, col)

# padding
image = np.pad(image, 1, 'constant', constant_values=0)

# input kernel size
krow = int(input("Enter the number of rows of kernel:"))
kcol = int(input("Enter the number of columns of kernel:"))

# input the stride size
stride = int(input("Enter the stride size:"))

# output with same image
stepcount = 1
for i in range(1, row+1, stride):
    for j in range(1, col+1, stride):
        sum = np.sum(image[i-1:i+krow-1, j-1:j+kcol-1])
        avg = sum/(krow*kcol)
        
        frac = avg - np.floor(avg)
        if frac < 0.5:
            roundup = np.floor(avg)
        else:
            roundup = np.ceil(avg)
            
        print("Step", stepcount, ":", " Sum =", sum, "Average = ",avg," Round up-->", roundup)
        stepcount += 1
        image[i][j] = roundup


# remove padding
image = image[1:row+1, 1:col+1]
print(image)

Enter the entries in a single line (separated by space): 
Step 1 :  Sum = 20 Average =  2.2222222222222223  Round up--> 2.0
Step 2 :  Sum = 38 Average =  4.222222222222222  Round up--> 4.0
Step 3 :  Sum = 33 Average =  3.6666666666666665  Round up--> 4.0
Step 4 :  Sum = 32 Average =  3.5555555555555554  Round up--> 4.0
Step 5 :  Sum = 23 Average =  2.5555555555555554  Round up--> 3.0
Step 6 :  Sum = 26 Average =  2.888888888888889  Round up--> 3.0
Step 7 :  Sum = 44 Average =  4.888888888888889  Round up--> 5.0
Step 8 :  Sum = 49 Average =  5.444444444444445  Round up--> 5.0
Step 9 :  Sum = 48 Average =  5.333333333333333  Round up--> 5.0
Step 10 :  Sum = 33 Average =  3.6666666666666665  Round up--> 4.0
Step 11 :  Sum = 23 Average =  2.5555555555555554  Round up--> 3.0
Step 12 :  Sum = 32 Average =  3.5555555555555554  Round up--> 4.0
Step 13 :  Sum = 36 Average =  4.0  Round up--> 4.0
Step 14 :  Sum = 38 Average =  4.222222222222222  Round up--> 4.0
Step 15 :  Sum = 25 Average =  2.7

In [1]:
#weighted filter(Linear)
import numpy as np

# input 2D array
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
print("Enter the Image entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
image = np.array(entries).reshape(row, col)

# padding
image = np.pad(image, 1, 'constant', constant_values=0)

# input kernel size
krow = int(input("Enter the number of rows of kernel:"))
kcol = int(input("Enter the number of columns of kernel:"))
print("Enter the Kernal entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
weight = np.array(entries).reshape(krow, kcol)
div = np.sum(weight)


# input the stride size
stride = int(input("Enter the stride size:"))


# output with same image
stepcount = 1
for i in range(1, row+1, stride):
    for j in range(1, col+1, stride):
        sum = np.sum(image[i-1:i+krow-1, j-1:j+kcol-1]*weight)
        avg = sum/div
        
        frac = avg - np.floor(avg)
        if frac < 0.5:
            roundup = np.floor(avg)
        else:
            roundup = np.ceil(avg)
            
        print("Step", stepcount, ":", " Sum =", sum, "Average = ",avg," Round up-->", roundup)
        stepcount += 1
        image[i][j] = roundup

# remove padding
image = image[1:row+1, 1:col+1]
print(image)


Enter the Image entries in a single line (separated by space): 
Enter the Kernal entries in a single line (separated by space): 
Step 1 :  Sum = 1240 Average =  77.5  Round up--> 78.0
Step 2 :  Sum = 638 Average =  39.875  Round up--> 40.0
Step 3 :  Sum = 704 Average =  44.0  Round up--> 44.0
Step 4 :  Sum = 888 Average =  55.5  Round up--> 56.0
Step 5 :  Sum = 884 Average =  55.25  Round up--> 55.0
Step 6 :  Sum = 934 Average =  58.375  Round up--> 58.0
Step 7 :  Sum = 856 Average =  53.5  Round up--> 54.0
Step 8 :  Sum = 1435 Average =  89.6875  Round up--> 90.0
Step 9 :  Sum = 975 Average =  60.9375  Round up--> 61.0
Step 10 :  Sum = 1181 Average =  73.8125  Round up--> 74.0
Step 11 :  Sum = 1502 Average =  93.875  Round up--> 94.0
Step 12 :  Sum = 1209 Average =  75.5625  Round up--> 76.0
Step 13 :  Sum = 901 Average =  56.3125  Round up--> 56.0
Step 14 :  Sum = 1072 Average =  67.0  Round up--> 67.0
Step 15 :  Sum = 1481 Average =  92.5625  Round up--> 93.0
Step 16 :  Sum = 1825 A

In [33]:
#Median filter(Non-Linear)
import numpy as np

# input 2D array
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
image = np.array(entries).reshape(row, col)

# padding
image = np.pad(image, 1, 'constant', constant_values=0)

# input kernel size
krow = int(input("Enter the number of rows of kernel:"))
kcol = int(input("Enter the number of columns of kernel:"))

# input the stride size
stride = int(input("Enter the stride size:"))

# output with same image
stepcount = 1
for i in range(1, row+1, stride):
    for j in range(1, col+1, stride):
        median = np.median(image[i-1:i+krow-1, j-1:j+kcol-1])
        print("Step", stepcount, ":", " Median =", median)
        stepcount += 1
        image[i][j] = median

# remove padding
image = image[1:row+1, 1:col+1]
print(image)


Enter the entries in a single line (separated by space): 
Step 1 :  Median = 0.0
Step 2 :  Median = 4.0
Step 3 :  Median = 4.0
Step 4 :  Median = 4.0
Step 5 :  Median = 0.0
Step 6 :  Median = 4.0
Step 7 :  Median = 4.0
Step 8 :  Median = 4.0
Step 9 :  Median = 5.0
Step 10 :  Median = 4.0
Step 11 :  Median = 4.0
Step 12 :  Median = 4.0
Step 13 :  Median = 4.0
Step 14 :  Median = 4.0
Step 15 :  Median = 4.0
Step 16 :  Median = 1.0
Step 17 :  Median = 1.0
Step 18 :  Median = 1.0
Step 19 :  Median = 2.0
Step 20 :  Median = 2.0
Step 21 :  Median = 0.0
Step 22 :  Median = 0.0
Step 23 :  Median = 0.0
Step 24 :  Median = 0.0
Step 25 :  Median = 0.0
[[0 4 4 4 0]
 [4 4 4 5 4]
 [4 4 4 4 4]
 [1 1 1 2 2]
 [0 0 0 0 0]]


In [34]:
#Max filter(Non-Linear)
import numpy as np

# input 2D array
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
image = np.array(entries).reshape(row, col)

# padding
image = np.pad(image, 1, 'constant', constant_values=0)

# input kernel size
krow = int(input("Enter the number of rows of kernel:"))
kcol = int(input("Enter the number of columns of kernel:"))

# input the stride size
stride = int(input("Enter the stride size:"))

# output with same image
stepcount = 1
for i in range(1, row+1, stride):
    for j in range(1, col+1, stride):
        max = np.max(image[i-1:i+krow-1, j-1:j+kcol-1])
        print("Step", stepcount, ":", " Max =", max)
        stepcount += 1
        image[i][j] = max

# remove padding
image = image[1:row+1, 1:col+1]
print(image)

Enter the entries in a single line (separated by space): 
Step 1 :  Max = 8
Step 2 :  Max = 9
Step 3 :  Max = 9
Step 4 :  Max = 9
Step 5 :  Max = 9
Step 6 :  Max = 9
Step 7 :  Max = 9
Step 8 :  Max = 9
Step 9 :  Max = 9
Step 10 :  Max = 9
Step 11 :  Max = 9
Step 12 :  Max = 9
Step 13 :  Max = 9
Step 14 :  Max = 9
Step 15 :  Max = 9
Step 16 :  Max = 9
Step 17 :  Max = 9
Step 18 :  Max = 9
Step 19 :  Max = 9
Step 20 :  Max = 9
Step 21 :  Max = 9
Step 22 :  Max = 9
Step 23 :  Max = 9
Step 24 :  Max = 9
Step 25 :  Max = 9
[[8 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [35]:
#Min filter(Non-Linear)
import numpy as np

# input 2D array
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
image = np.array(entries).reshape(row, col)

# padding
image = np.pad(image, 1, 'constant', constant_values=0)

# input kernel size
krow = int(input("Enter the number of rows of kernel:"))
kcol = int(input("Enter the number of columns of kernel:"))

# input the stride size
stride = int(input("Enter the stride size:"))

# output with same image
stepcount = 1
for i in range(1, row+1, stride):
    for j in range(1, col+1, stride):
        min = np.min(image[i-1:i+krow-1, j-1:j+kcol-1])
        print("Step", stepcount, ":", " Min =", min)
        stepcount += 1
        image[i][j] = min

# remove padding
image = image[1:row+1, 1:col+1]
print(image)

Enter the entries in a single line (separated by space): 
Step 1 :  Min = 0
Step 2 :  Min = 0
Step 3 :  Min = 0
Step 4 :  Min = 0
Step 5 :  Min = 0
Step 6 :  Min = 0
Step 7 :  Min = 0
Step 8 :  Min = 0
Step 9 :  Min = 0
Step 10 :  Min = 0
Step 11 :  Min = 0
Step 12 :  Min = 0
Step 13 :  Min = 0
Step 14 :  Min = 0
Step 15 :  Min = 0
Step 16 :  Min = 0
Step 17 :  Min = 0
Step 18 :  Min = 0
Step 19 :  Min = 0
Step 20 :  Min = 0
Step 21 :  Min = 0
Step 22 :  Min = 0
Step 23 :  Min = 0
Step 24 :  Min = 0
Step 25 :  Min = 0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
