<h4>Task-1: Take three float values in three variables by user input and find out the sum of three values.</h4>

In [1]:
a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))
c = float(input("Enter the third number: "))
sum = a + b + c
print("The sum of three numbers is: ", sum)

Sum of three numbers is 1.21.41.4


<h4>Task-2:Take three lists, print them and find out the sum of three lists. </h4>

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = [11, 12, 13, 14, 15]
print("List 1: ", list1)
print("List 2: ", list2)
print("List 3: ", list3)
sum = list1 + list2 + list3
print("The sum of three lists is: ", sum)


<h4>Task-3: Print the sum of first 100 numbers using for loop, while loop and do while loop.</h4>

In [2]:
# For loop
sum = 0
for i in range(1, 101):
    sum += i
print("The sum of first 100 numbers using for loop is: ", sum)

# While loop
sum = 0
i = 1
while i <= 100:
    sum += i
    i += 1
print("The sum of first 100 numbers using while loop is: ", sum)

# Do while loop
sum = 0
i = 1
while True:
    sum += i
    i += 1
    if i > 100:
        break
print("The sum of first 100 numbers using do while loop is: ", sum)


The sum of first 100 numbers using for loop is:  5050
The sum of first 100 numbers using while loop is:  5050
The sum of first 100 numbers using do while loop is:  5050


<h4>Task-4: Print the Fibonacci series using for loop.</h4>

In [5]:
a = 0
b = 1
print("Fibonacci series using for loop: ")
for i in range(1, 20):
    print(a, end = " ")
    c = a + b
    a = b
    b = c


Fibonacci series using for loop: 
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 

<h4>Task-5: Take three strings as user input, print them and concatenate them.</h4>

In [6]:
a = input("Enter the first string: ")
b = input("Enter the second string: ")
c = input("Enter the third string: ")
print("The three strings are: ", a, b, c)
print("The concatenated string is: ", a + b + c)

The three strings are:  This is BAUET
The concatenated string is:  ThisisBAUET


<h4>Task-6: Perform String Slicing operation: Slice From the Start, Slice To the End and slicing using Negative
Indexing.</h4>

In [7]:
a = "Hello World"
print("The string is: ", a)
print("Slicing from the start: ", a[:5])
print("Slicing to the end: ", a[6:])
print("Slicing using negative indexes: ", a[-5:-1])

The string is:  Hello World
Slicing from the start:  Hello
Slicing to the end:  World
Slicing using negative indexes:  Worl


<h4>Task-7: Determine the grade of a student using if..else logic if subject number is taken as user input.</h4>

In [8]:
marks = int(input("Enter the marks: "))
if marks >= 90:
    print("Grade: A")
elif marks >= 80:
    print("Grade: B")
elif marks >= 70:
    print("Grade: C")
elif marks >= 60:
    print("Grade: D")
elif marks >= 50:
    print("Grade: E")
else:
    print("Grade: F")


Grade: A


<h4>Task-8: Determine the grade of a student using switch..case logic if subject number is taken as user input.</h4>

In [10]:
grade_dict = {
    range(90, 101): "A",
    range(80, 90): "B",
    range(70, 80): "C",
    range(60, 70): "D",
    range(50, 60): "E",
    range(0, 50): "F"
}

marks = int(input("Enter the marks: "))

for key in grade_dict:
    if marks in key:
        print("Grade:", grade_dict[key])
        break

Grade: B


<h4>Task-9: Take four NumPy arrays (nparray1, nparray2, nparray3, nparray4). Define nparray1=[[1,2,3,4],
[5,6,7,8]]), nparray2 = [5,6,7,8], nparray3 as zeros of dimension (3,4) and nparray4 as ones of dimension (3,7). Now perform NumPy array slicing: selecting 1st 2 rows and 1st two columns, first element, middle element and last element individually.</h4>

In [11]:
import numpy as np

nparray1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
nparray2 = np.array([5, 6, 7, 8])
nparray3 = np.zeros((3, 4))
nparray4 = np.ones((3, 7))

print("nparray1: ", nparray1)
print("nparray2: ", nparray2)
print("nparray3: ", nparray3)
print("nparray4: ", nparray4)

print("Slicing nparray1: ", nparray1[:2, :2])
print("Slicing nparray2: ", nparray2[0])
print("Slicing nparray3: ", nparray3[1, 2])
print("Slicing nparray4: ", nparray4[2, 3])



nparray1:  [[1 2 3 4]
 [5 6 7 8]]
nparray2:  [5 6 7 8]
nparray3:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
nparray4:  [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
Slicing nparray1:  [[1 2]
 [5 6]]
Slicing nparray2:  5
Slicing nparray3:  0.0
Slicing nparray4:  1.0
